apiVersion: v1
data:
  mapRoles: |
    mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::670643698904:role/UdacityFlaskDeployCBKubectlRole
      username: build   
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::670643698904:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-U7JUIBY9YVA8
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: '2022-07-07T18:31:24Z'
  name: aws-auth
  namespace: kube-system
  resourceVersion: '1547'
  uid: 49063c19-2d98-4c78-b261-5d2b223ca7ec
