apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::098407932799:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-OEPI1X9TX048
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-04-27T11:51:47Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1020"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 792008e4-887d-11ea-84ad-02806aa53476
