POST  http://localhost:80/auth HTTP/1.1
content-type: application/json

{"email":"kcemenike@live.com","password":"chucakfd"}

GET http://localhost:80/contents HTTP/1.1
ontent-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1ODkxNzY2NTMsIm5iZiI6MTU4Nzk2NzA1MywiZW1haWwiOiJrY2VtZW5pa2VAbGl2ZS5jb20ifQ._ZiPYUBcX4JzkJn1fLKMtWh7MXl0JIF5Ds3a4Dfp9P8
